; PlatformIO Project Configuration File for AeroLog-RTOS
; Dual-Target Support: STM32 Black Pill (Cortex-M4) & ESP32 DevKit

[platformio]
default_envs = blackpill_f401cc

[env:blackpill_f401cc]
platform = ststm32
board = blackpill_f401cc
framework = arduino
upload_protocol = stlink
monitor_speed = 115200

build_flags =
    -Iinclude
    -O2
    -Wall
    -Wextra
    -DARDUINO_BLACKPILL_F401CC

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

build_flags =
    -Iinclude
    -O2
    -Wall
    -Wextra

; Native Host Simulation & Test Environment
[env:native]
platform = native
build_flags =
    -Iinclude
    -Itests
    -lm
